baseurl = "/"
languageCode = "en-us"
publishDir = "docs"
# canonifyurls = true
theme = "kiera"

newContentEditor = "C:\\Program Files (x86)\\Notepad++\\notepad++.exe"

## Hugo Built-in Features
disqusShortname = "superdotnet"
googleAnalytics = "UA-121100023-2"
enableRobotsTXT = true


title = "Super.NET Blog, Dawg"
copyright = "&copy; 2018 Super.NET"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Mike-EEE"
    github = "SuperDotNet"
    facebook = "RunSuperDotNet"
    twitter = "RunSuperDotNet"
	email = "run@superdotnet.run"

[permalinks]
  posts = "/:year/:month/:title/"
	
[params]
    tagline = "Words on the brave path towards a ubiquitous .NET client model."
	
## Main Menu
[[menu.main]]
    name = "Super.NET"
    weight = 1
    identifier = "superdotnet"
    url = "https://superdotnet.run"
